[package]
name = "dyn_serde"
version = "0.1.0"
authors = ["Huang Yifan"]
edition = "2021"
description = "dynamic serialization and deserialization based on serde"
readme = "README.md"
repository = "https://github.com/HyfLink/dyn_serde"
license = "MIT OR Apache-2.0"
keywords = ["serde", "no_std"]
categories = ["encoding", "no-std"]

[features]
default = ["error"]
std = ["serde/std"]
# Disabling this feature will discard the error message on the failure of the
# dynamic serialization and deserialization.
error = []

[dependencies]
serde = { version = "1.0.216", default-features = false }

[dev-dependencies]
serde_json = "1.0.133"
